[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@fhevm/=node_modules/@fhevm/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@zama-fhe/=node_modules/@zama-fhe/",
    "encrypted-types/=node_modules/encrypted-types/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
